# Generated by Django 4.2 on 2023-04-28 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bsrent_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rented_vehicles', to='bsrent_app.vehicle'),
        ),
        migrations.AlterField(
            model_name='vehicleatstation',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='bsrent_app.station'),
        ),
        migrations.AlterField(
            model_name='vehicleatstation',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_vehicles', to='bsrent_app.vehicle'),
        ),
    ]
