# Generated by Django 4.2 on 2023-04-28 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bsrent_app', '0002_alter_rental_vehicle_alter_vehicleatstation_station_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='rental_return_date',
            new_name='return_date',
        ),
        migrations.RenameField(
            model_name='rental',
            old_name='rental_start_date',
            new_name='start_date',
        ),
    ]
