# Generated by Django 4.2 on 2023-04-28 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bsrent_app', '0003_rename_rental_return_date_rental_return_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_rental', to='bsrent_app.customer'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles_rentals', to='bsrent_app.vehicle'),
        ),
        migrations.AlterField(
            model_name='vehicleatstation',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_at_station', to='bsrent_app.station'),
        ),
        migrations.AlterField(
            model_name='vehicleatstation',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles_station_record', to='bsrent_app.vehicle'),
        ),
    ]
