# Generated by Django 4.2 on 2023-04-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifs_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='gifs',
        ),
        migrations.AddField(
            model_name='gif',
            name='category',
            field=models.ManyToManyField(to='gifs_app.category'),
        ),
    ]
