# Generated by Django 4.2 on 2023-04-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifs_app', '0002_remove_category_gifs_gif_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gif',
            name='category',
            field=models.ManyToManyField(blank=True, to='gifs_app.category'),
        ),
    ]
