# Generated by Django 4.2.1 on 2023-05-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0004_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('dep_adm', 'Department Admin'), ('hr', 'Human Resource'), ('proj_admin', 'Project admin')], max_length=10, null=True),
        ),
    ]
