# Generated by Django 4.2 on 2023-04-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='imageurl',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='speed',
            field=models.FloatField(null=True),
        ),
    ]
