# Generated by Django 4.2 on 2023-05-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='weather_type',
            field=models.CharField(choices=[('sunny', 'Sunny'), ('cloudy', 'Storm'), ('windy', 'Sunny'), ('rainy', 'Rainy'), ('stormy', 'Stormy')], max_length=8, null=True),
        ),
    ]
